### PR TITLE
[wip] Add Android plugin for Text

### PR DESCRIPTION
**Pull request by craiglabenz**
## Description

Adds the beginning scaffolding for the `mediapipe_task_text` library, including the `mediapipe_task_text_platform_implementation` and `mediapipe_task_text_android` libraries.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/google/flutter-mediapipe/issues
[Contributor Guide]: https://github.com/google/flutter-mediapipe/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by PaulTR** [comment]
We should probably move the app in example down a layer since the text plugin includes things like text classification, language detector, and text embedding.

**Comment by craiglabenz** [comment]
> We should probably move the app in example down a layer since the text plugin includes things like text classification, language detector, and text embedding.

Do you think it's important to have separate samples for each work flow, or could they potentially be lumped into one demo with 3 different buttons to complete each task?

**Comment by PaulTR** [comment]
I'd keep them separated. We have one example per task in the other
platforms, so keeping them separated helps us add examples for each over
time

**Comment by craiglabenz** [comment]
The latest commit *should* be working (or at least close to) from an implementation standpoint, but I'm getting segfault-like errors in my Android emulator.

**Comment by craiglabenz** [comment]
So obsolete, you can't even imagine.

**Pull request closed without merging**
